CREATE TABLE IF NOT EXISTS `wp_forum_topics` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`title`  varchar(300) NOT NULL   COMMENT '标题',
`content`  varchar(1500) NOT NULL   COMMENT '内容',
`likeid`  varchar(3000) NULL   COMMENT '喜欢数',
`commentid`  varchar(3000) NULL   COMMENT '评论数',
`favourid`  varchar(3000) NULL   COMMENT '点赞数',
`createtime`  int(11) NOT NULL   COMMENT '添加时间',
`updatetime`  int(11) NULL   COMMENT '更新时间',
`uid`  varchar(50) NULL   COMMENT '用户ID',
`uname`  varchar(50) NULL   COMMENT '用户名称',
`token`  varchar(50) NULL   COMMENT 'token',
`photos`  varchar(300) NULL   COMMENT '图片',
`status`  tinyint(4) NOT NULL   COMMENT '状态',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('forum_topics','微论坛-帖子','0','','1','{"1":["title","content","photos"]}','1:基础','','','','','id:5%ID\r\nuname:20%发帖人\r\ntitle:30%标题\r\nfavourid:5%赞\r\nlikeid:5%喜欢\r\ncreatetime|time_format:15%创建时间\r\nstatus|get_name_by_status:10%状态\r\nid:10%操作:checkTopics?model=topics&id=[id]|审核,del?model=topics&id=[id]|删除','10','title','','1405769371','1405962063','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','标题','varchar(300) NOT NULL ','string','','','1','','0','1','1','1405964301','1405769371','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','内容','varchar(1500) NOT NULL ','textarea','','','1','','0','1','1','1405964294','1405769371','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('likeid','喜欢数','varchar(3000) NULL ','num','','','3','','0','0','1','1405964287','1405769371','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('commentid','评论数','varchar(3000) NULL ','num','','','3','','0','0','1','1405964278','1405769371','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('favourid','点赞数','varchar(3000) NULL ','num','','','3','','0','0','1','1405964270','1405769371','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('createtime','添加时间','int(11) NOT NULL ','datetime','','','0','','0','0','1','1405964197','1405769371','','3','','regex','time','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('updatetime','更新时间','int(11) NULL ','datetime','','','0','','0','0','1','1405964244','1405769371','','3','','regex','time','2','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uid','用户ID','varchar(50) NULL ','string','','','0','','0','0','1','1405964234','1405769371','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uname','用户名称','varchar(50) NULL ','string','','','0','','0','0','1','1405964225','1405769371','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(50) NULL ','string','','','0','','0','0','1','1405830796','1405769371','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('photos','图片','varchar(300) NULL ','string','','','0','','0','0','1','1405964208','1405769371','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','状态','tinyint(4) NOT NULL ','select','','','1','-1:未审核\r\n0:已删除\r\n1:正常显示','0','0','1','1405964795','1405769371','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_forum_comment` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`tid`  int(11) NOT NULL   COMMENT '帖子编号',
`uid`  varchar(50) NULL   COMMENT 'uid',
`uname`  varchar(50) NULL   COMMENT '评论人',
`content`  varchar(3000) NOT NULL   COMMENT '内容',
`createtime`  int(11) NOT NULL   COMMENT '发布时间',
`favourid`  varchar(3000) NULL   COMMENT '点赞数',
`replyid`  varchar(3000) NULL   COMMENT '回复数',
`status`  tinyint(4) NOT NULL   COMMENT '状态',
`token`  varchar(50) NULL   COMMENT 'token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('forum_comment','微论坛-评论','0','','1','{"1":["tid","uid","uname","content","createtime","favourid","replyid","status","token"]}','1:基础','','','','','id:5%ID\r\nuname:10%评论人\r\ncontent:45%内容\r\nfavourid:5%赞\r\ncreatetime|time_format:15%创建时间\r\nstatus|get_name_by_status:10%状态\r\nid:10%操作:checkTopics?model=comment&id=[id]|审核,del?model=comment&id=[id]|删除','10','uname','','1405769439','1405961893','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('tid','帖子编号','int(11) NOT NULL ','string','','','1','','0','0','1','1405963217','1405769439','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uid','uid','varchar(50) NULL ','string','','','1','','0','0','1','1405963206','1405769439','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('uname','评论人','varchar(50) NULL ','string','','','1','','0','0','1','1405963175','1405769439','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','内容','varchar(3000) NOT NULL ','string','','','1','','0','0','1','1405963152','1405769439','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('createtime','发布时间','int(11) NOT NULL ','string','','','1','','0','0','1','1405963144','1405769439','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('favourid','点赞数','varchar(3000) NULL ','string','','','1','','0','0','1','1405963134','1405769439','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('replyid','回复数','varchar(3000) NULL ','string','','','1','','0','0','1','1405963098','1405769439','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','状态','tinyint(4) NOT NULL ','select','','','1','-1:未审核\r\n0:已删除\r\n1:正常显示','0','0','1','1405960954','1405769439','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(50) NULL ','string','','','1','','0','0','1','1405963014','1405769439','','0','','regex','','0','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_forum_message` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`fromuname`  varchar(60) NULL   COMMENT '发送人',
`cid`  int(11) NULL   COMMENT 'cid',
`token`  varchar(50) NULL   COMMENT 'token',
`tid`  int(11) NULL   COMMENT '帖子编号',
`touname`  varchar(60) NULL   COMMENT '接收人',
`touid`  varchar(40) NOT NULL   COMMENT '接收ID',
`fromuid`  varchar(50) NOT NULL   COMMENT '发送ID',
`createtime`  int(11) NOT NULL   COMMENT '发表时间',
`content`  varchar(3000) NOT NULL   COMMENT '内容',
`status`  tinyint(4) NOT NULL   DEFAULT 1 COMMENT '状态',
`isread`  tinyint(4) NOT NULL   DEFAULT 1 COMMENT '是否查看',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('forum_message','微论坛-消息','0','','1','{"1":["content","createtime","fromuid","touid","fromuname","touname","tid","cid","token","status","isread"]}','1:基础','','','','','id:5%ID\r\nfromuname:10%发送人\r\ntouname:10%接收人\r\ncontent:40%内容\r\ncreatetime|time_format:15%创建时间\r\nstatus|get_name_by_status:10%状态\r\nid:10%操作:del?model=message&id=[id]|删除','10','','','1405769561','1405963450','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('fromuname','发送人','varchar(60) NULL ','string','','','1','','0','0','1','1406002855','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cid','cid','int(11) NULL ','string','','','1','','0','0','1','1406003048','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(50) NULL ','string','','','1','','0','0','1','1406003059','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('tid','帖子编号','int(11) NULL ','string','','','1','','0','0','1','1406003039','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('touname','接收人','varchar(60) NULL ','string','','','1','','0','0','1','1406002867','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('touid','接收ID','varchar(40) NOT NULL ','string','','','1','','0','0','1','1406002833','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('fromuid','发送ID','varchar(50) NOT NULL ','string','','','1','','0','0','1','1406002820','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('createtime','发表时间','int(11) NOT NULL ','string','','','1','','0','0','1','1406002798','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','内容','varchar(3000) NOT NULL ','string','','','1','','0','0','1','1406002581','1405769561','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','状态','tinyint(4) NOT NULL ','select','1','','1','-1:未审核\r\n0:已删除\r\n1:正常显示','0','0','1','1406002711','1405769561','','0','','regex','','0','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('isread','是否查看','tinyint(4) NOT NULL ','select','1','','1','0:已读\r\n1:未读','0','0','1','1406003158','1405769561','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

